# Generated by Django 5.2.17 on 2026-10-01 17:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('modality', models.CharField(max_length=32)),
                ('status', models.CharField(default='ordered', max_length=16)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('performed_at', models.DateTimeField(null=True)),
                ('report_time', models.DateTimeField(null=True)),
                ('dicom_study_uid', models.CharField(max_length=128, null=True)),
            ],
            options={
                'db_table': 'ris.order',
            },
        ),
    ]
