# Generated by Django 5.2.17 on 2026-10-02 06:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ABHACallbackLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('request_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('facility_abdm_id', models.CharField(db_index=True, max_length=64)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('profile', models.JSONField(null=True)),
                ('matched_patient_id', models.UUIDField(blank=True, null=True)),
                ('token_issued', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'abdm.callback_log',
                'indexes': [models.Index(fields=['tenant_id', 'request_id'], name='abdm.callba_tenant__141b3a_idx')],
            },
        ),
    ]
