# Generated by Django 5.2.17, then extended with the tenant_id backfill.
#
# Expand phase of the tenancy fix. tenant_id is added nullable here and backfilled
# from the owning parent row; migration 0003 tightens it to NOT NULL. The split is
# deliberate: PostgreSQL cannot add a NOT NULL column to a populated table, and a
# default would be a guess at which tenant owns each row - the cross-tenant
# leakage the architecture doc section 7 names as the top risk.
from django.db import migrations, models

from common.tenant_migration import assert_no_orphans, backfill_tenant_id


def forwards(apps, schema_editor):
    # billing.payment derives its tenant from billing.invoice.invoice_id.
    backfill_tenant_id(
        target_table='billing.payment',
        parent_table='billing.invoice',
        parent_column='invoice_id',
    )
    # billing.claim derives its tenant from billing.invoice.invoice_id.
    backfill_tenant_id(
        target_table='billing.claim',
        parent_table='billing.invoice',
        parent_column='invoice_id',
    )
    assert_no_orphans(target_table='billing.payment')
    assert_no_orphans(target_table='billing.claim')


def backwards(apps, schema_editor):
    # Reversing only drops the column; the rows themselves are untouched.
    pass



class Migration(migrations.Migration):

    dependencies = [
        ('billing_insurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='tenant_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['tenant_id', 'status', 'invoice_id'], name='billing.cla_tenant__d8c0db_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant_id', 'invoice_id', 'paid_at'], name='billing.pay_tenant__a39eb4_idx'),
        ),
        migrations.RunPython(forwards, backwards),
    ]
