# Generated by Django 5.2.17 on 2026-10-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_insurance', '0002_claim_tenant_id_payment_tenant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='tenant_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tenant_id',
            field=models.UUIDField(db_index=True),
        ),
    ]
