# Generated by Django 5.2.17 on 2026-10-01 17:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('theatre', models.CharField(max_length=64)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('surgeon_id', models.UUIDField(null=True)),
                ('anaesthetist_id', models.UUIDField(null=True)),
                ('scheduled_start', models.DateTimeField(db_index=True)),
                ('scheduled_end', models.DateTimeField(null=True)),
                ('conflict_detected', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ot.schedule',
            },
        ),
        migrations.CreateModel(
            name='SurgeryRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_id', models.UUIDField(db_index=True)),
                ('pre_op_checklist', models.JSONField(null=True)),
                ('anaesthesia_record', models.JSONField(null=True)),
                ('operative_note', models.TextField(null=True)),
                ('prophylaxis_time', models.DateTimeField(null=True)),
                ('incision_time', models.DateTimeField(null=True)),
                ('unplanned_return', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ot.record',
            },
        ),
    ]
