# Generated by Django 5.2.17, then extended with the tenant_id backfill.
#
# Expand phase of the tenancy fix. tenant_id is added nullable here and backfilled
# from the owning parent row; migration 0003 tightens it to NOT NULL. The split is
# deliberate: PostgreSQL cannot add a NOT NULL column to a populated table, and a
# default would be a guess at which tenant owns each row - the cross-tenant
# leakage the architecture doc section 7 names as the top risk.
from django.db import migrations, models

from common.tenant_migration import assert_no_orphans, backfill_tenant_id


def forwards(apps, schema_editor):
    # ot.record derives its tenant from ot.schedule.schedule_id.
    backfill_tenant_id(
        target_table='ot.record',
        parent_table='ot.schedule',
        parent_column='schedule_id',
    )
    assert_no_orphans(target_table='ot.record')


def backwards(apps, schema_editor):
    # Reversing only drops the column; the rows themselves are untouched.
    pass



class Migration(migrations.Migration):

    dependencies = [
        ('ot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgeryrecord',
            name='tenant_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='surgeryrecord',
            index=models.Index(fields=['tenant_id', 'schedule_id', 'incision_time'], name='ot.record_tenant__d97905_idx'),
        ),
        migrations.RunPython(forwards, backwards),
    ]
