"""Append the tenant_id backfill step to each generated expand migration.

The 0002 migrations created by makemigrations add tenant_id as nullable so the
NOT NULL constraint is not created in the same step as the backfill. This
inserts the RunPython that fills it in, after the column exists and before the
0003 contract migration runs.

The parent chains below are the real ownership edges in the models; each one
lets the owning tenant be derived from a row that is already tenant-scoped.
"""
import pathlib
import re

BACKEND = pathlib.Path(__file__).resolve().parent.parent / "apps"

# module -> (migration filename, {target_table: (parent_table, parent_column)})
PLAN = {
    "identity_tenancy": (
        "0002_bed_tenant_id_serviceunit_tenant_id_and_more.py",
        {
            "identity.ward": ("identity.department", "department_id"),
            "identity.bed": ("identity.ward", "ward_id"),
            "identity.service_unit": ("identity.facility", "facility_id"),
            "identity.staff_position": ("identity.department", "department_id"),
        },
    ),
    "patient_registry": (
        "0002_intakepoint_tenant_id_qrcode_tenant_id_and_more.py",
        {
            "registry.intake_point": ("identity.facility", "facility_id"),
            "registry.qr_code": ("identity.facility", "facility_id"),
        },
    ),
    "opd": (
        "0002_opdencounter_tenant_id_and_more.py",
        {"opd.encounter": ("registry.patient", "patient_id")},
    ),
    "ipd": (
        "0002_bedstatus_tenant_id_and_more.py",
        {"ipd.bed_status": ("identity.bed", "bed_id")},
    ),
    "icu": (
        "0002_device_tenant_id_and_more.py",
        {"icu.device": ("ipd.admission", "admission_id")},
    ),
    "ot": (
        "0002_surgeryrecord_tenant_id_and_more.py",
        {"ot.record": ("ot.schedule", "schedule_id")},
    ),
    "lis": (
        "0002_labresult_tenant_id_and_more.py",
        {"lis.result": ("lis.order", "order_id")},
    ),
    "pharmacy": (
        "0002_dispense_tenant_id_stockbatch_tenant_id_and_more.py",
        {
            "pharmacy.stock_batch": ("pharmacy.formulary", "formulary_id"),
            "pharmacy.dispense": ("registry.patient", "patient_id"),
        },
    ),
    "blood_bank": (
        "0002_crossmatch_tenant_id_donation_tenant_id_and_more.py",
        {
            "bbk.donation": ("bbk.donor", "donor_id"),
            "bbk.crossmatch": ("bbk.requisition", "requisition_id"),
            "bbk.reaction": ("bbk.requisition", "requisition_id"),
        },
    ),
    "billing_insurance": (
        "0002_claim_tenant_id_payment_tenant_id_and_more.py",
        {
            "billing.payment": ("billing.invoice", "invoice_id"),
            "billing.claim": ("billing.invoice", "invoice_id"),
        },
    ),
    "emr": (
        "0002_problemlist_tenant_id_and_more.py",
        {"emr.problem": ("registry.patient", "patient_id")},
    ),
    # integration.adapter has no parent: its config holds per-tenant
    # credentials, so no existing row implies which tenant owns it.
    "integration": ("0002_integrationadapter_tenant_id_and_more.py", None),
}

HEADER = """# Generated by Django 5.2.17, then extended with the tenant_id backfill.
#
# Expand phase of the tenancy fix. tenant_id is added nullable here and backfilled
# from the owning parent row; migration 0003 tightens it to NOT NULL. The split is
# deliberate: PostgreSQL cannot add a NOT NULL column to a populated table, and a
# default would be a guess at which tenant owns each row - the cross-tenant
# leakage the architecture doc section 7 names as the top risk.
"""

RUNPYTHON_IMPORT = (
    "from common.tenant_migration import "
    "assert_no_orphans, backfill_tenant_id, require_empty"
)

# Extra dependencies the backfill needs. A RunPython reads the *parent* table
# with raw SQL, which the migration graph cannot infer from the model state, so
# an app backfilling from another app's table must declare that explicitly.
# Without these, migrate applies emr.0002 before patient_registry.0001 and the
# backfill fails with 'relation "registry.patient" does not exist'.
EXTRA_DEPENDENCIES = {
    # intake_point and qr_code derive their tenant from identity.facility
    "patient_registry": [("identity_tenancy", "0001_initial")],
    # opd.encounter derives from registry.patient
    "opd": [("patient_registry", "0001_initial")],
    # ipd.bed_status derives from identity.bed
    "ipd": [("identity_tenancy", "0001_initial")],
    # icu.device derives from ipd.admission
    "icu": [("ipd", "0001_initial")],
    # pharmacy.dispense derives from registry.patient
    "pharmacy": [("patient_registry", "0001_initial")],
    # emr.problem derives from registry.patient
    "emr": [("patient_registry", "0001_initial")],
}


def render_functions(tables) -> str:
    if tables is None:
        return '''
def forwards(apps, schema_editor):
    require_empty(target_table="integration.adapter")


def backwards(apps, schema_editor):
    # Reversing only drops the column; the rows themselves are untouched.
    pass
'''
    lines = ["", "", "def forwards(apps, schema_editor):"]
    for target, (parent, column) in tables.items():
        lines.append(f"    # {target} derives its tenant from {parent}.{column}.")
        lines.append("    backfill_tenant_id(")
        lines.append(f"        target_table={target!r},")
        lines.append(f"        parent_table={parent!r},")
        lines.append(f"        parent_column={column!r},")
        lines.append("    )")
    for target in tables:
        lines.append(f"    assert_no_orphans(target_table={target!r})")
    lines += [
        "",
        "",
        "def backwards(apps, schema_editor):",
        "    # Reversing only drops the column; the rows themselves are untouched.",
        "    pass",
    ]
    return "\n".join(lines) + "\n"


def patch(module: str, filename: str, tables) -> None:
    path = BACKEND / module / "migrations" / filename
    source = path.read_text(encoding="utf-8")

    # Drop the auto-generated timestamp comment; ours supersedes it.
    source = re.sub(r"(?m)^# Generated by Django .*\n", "", source, count=1)
    source = HEADER + source.lstrip("\n")

    # Add the helper import next to the existing django.db import.
    source = source.replace(
        "from django.db import migrations, models\n",
        "from django.db import migrations, models\n\n" + RUNPYTHON_IMPORT + "\n",
        1,
    )

    # Declare cross-app dependencies the raw-SQL backfill needs.
    extra = EXTRA_DEPENDENCIES.get(module)
    if extra:
        entries = "".join(f"        ({app!r}, {name!r}),\n" for app, name in extra)
        source = re.sub(
            r"(?s)(    dependencies = \[\n)(.*?)(    \]\n)",
            lambda m: m.group(1)
            + m.group(2)
            + entries
            + m.group(3),
            source,
            count=1,
        )

    # The functions must be defined *before* the class: the class body
    # evaluates `RunPython(forwards, backwards)` at import time.
    functions = render_functions(tables)
    class_at = source.index("class Migration(migrations.Migration):")
    source = source[:class_at] + functions.lstrip("\n") + "\n\n\n" + source[class_at:]

    # Insert RunPython as the final operation, so every tenant_id column the
    # migration adds already exists when the backfill runs. It goes *inside* the
    # operations list, immediately before its closing bracket.
    marker = "    operations = ["
    start = source.index(marker)
    close = "\n    ]\n"
    end = source.index(close, start)
    source = (
        source[:end]
        + "\n        migrations.RunPython(forwards, backwards),"
        + source[end:]
    )

    path.write_text(source, encoding="utf-8")
    print(f"  patched {module}/{filename}")


if __name__ == "__main__":
    for name, (filename, tables) in PLAN.items():
        patch(name, filename, tables)
    print(f"{len(PLAN)} migration(s) updated")