# Generated by Django 5.2.17 on 2026-10-02 06:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0004_enable_row_level_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('filename', models.CharField(max_length=500)),
                ('file_url', models.URLField()),
                ('file_type', models.CharField(max_length=64)),
                ('uploaded_by', models.UUIDField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'platform.file',
            },
        ),
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('job_type', models.CharField(max_length=64)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('scheduled_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'platform.scheduled_job',
            },
        ),
        migrations.DeleteModel(
            name='FeatureFlag',
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant_id', 'user_id', 'read_at'], name='platform.no_tenant__d4c14e_idx'),
        ),
        migrations.AddIndex(
            model_name='platformfile',
            index=models.Index(fields=['tenant_id', 'uploaded_at'], name='platform.fi_tenant__fcb739_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledjob',
            index=models.Index(fields=['tenant_id', 'status', 'scheduled_at'], name='platform.sc_tenant__7be0df_idx'),
        ),
    ]
