# Generated by Django 5.2.17 on 2026-10-01 17:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('test_code', models.CharField(max_length=64)),
                ('status', models.CharField(default='ordered', max_length=16)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('collection_time', models.DateTimeField(null=True)),
                ('receipt_time', models.DateTimeField(null=True)),
                ('report_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'lis.order',
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField(db_index=True)),
                ('result', models.JSONField()),
                ('critical', models.BooleanField(default=False)),
                ('acknowledged', models.BooleanField(default=False)),
                ('ack_time', models.DateTimeField(null=True)),
                ('released', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'lis.result',
            },
        ),
    ]
