# Generated by Django 5.2.17 on 2026-10-01 17:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity_tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABHACallbackLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('request_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('facility_abdm_id', models.CharField(db_index=True, max_length=64)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('profile', models.JSONField(null=True)),
                ('matched_patient_id', models.UUIDField(blank=True, null=True)),
                ('token_issued', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'registry.abdm_callback_log',
                'indexes': [models.Index(fields=['tenant_id', 'request_id'], name='registry.ab_tenant__88a1cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='IntakePoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=32)),
                ('counter_id', models.CharField(blank=True, max_length=32, null=True)),
                ('active', models.BooleanField(default=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_points', to='identity_tenancy.facility')),
            ],
            options={
                'db_table': 'registry.intake_point',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('uhid', models.CharField(db_index=True, max_length=32, unique=True)),
                ('abha_address', models.CharField(blank=True, max_length=128, null=True)),
                ('abha_number', models.CharField(blank=True, db_index=True, max_length=14, null=True)),
                ('verification_status', models.CharField(default='provisional', max_length=16)),
                ('demographics', models.JSONField()),
                ('contact', models.JSONField(null=True)),
                ('address', models.JSONField(null=True)),
                ('scheme_category', models.JSONField(null=True)),
                ('consent_flags', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'registry.patient',
                'indexes': [models.Index(fields=['tenant_id', 'abha_number'], name='registry.pa_tenant__097a2a_idx'), models.Index(fields=['tenant_id', 'uhid'], name='registry.pa_tenant__4aebb8_idx')],
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encode_data', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('regenerated_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='identity_tenancy.facility')),
                ('intake_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_codes', to='patient_registry.intakepoint')),
            ],
            options={
                'db_table': 'registry.qr_code',
            },
        ),
    ]
