# Generated by Django 5.2.17, then extended with the tenant_id backfill.
#
# Expand phase of the tenancy fix. tenant_id is added nullable here and backfilled
# from the owning parent row; migration 0003 tightens it to NOT NULL. The split is
# deliberate: PostgreSQL cannot add a NOT NULL column to a populated table, and a
# default would be a guess at which tenant owns each row - the cross-tenant
# leakage the architecture doc section 7 names as the top risk.
from django.db import migrations, models

from common.tenant_migration import assert_no_orphans, backfill_tenant_id


def forwards(apps, schema_editor):
    # registry.intake_point derives its tenant from identity.facility.facility_id.
    backfill_tenant_id(
        target_table='registry.intake_point',
        parent_table='identity.facility',
        parent_column='facility_id',
    )
    # registry.qr_code derives its tenant from identity.facility.facility_id.
    backfill_tenant_id(
        target_table='registry.qr_code',
        parent_table='identity.facility',
        parent_column='facility_id',
    )
    assert_no_orphans(target_table='registry.intake_point')
    assert_no_orphans(target_table='registry.qr_code')


def backwards(apps, schema_editor):
    # Reversing only drops the column; the rows themselves are untouched.
    pass



class Migration(migrations.Migration):

    dependencies = [
        ('identity_tenancy', '0002_bed_tenant_id_serviceunit_tenant_id_and_more'),
        ('patient_registry', '0001_initial'),
        ('identity_tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakepoint',
            name='tenant_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='tenant_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='uhid',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('tenant_id', 'uhid')},
        ),
        migrations.AddIndex(
            model_name='intakepoint',
            index=models.Index(fields=['tenant_id', 'facility', 'type'], name='registry.in_tenant__8f73ae_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['tenant_id', 'facility', 'active'], name='registry.qr_tenant__302add_idx'),
        ),
        migrations.RunPython(forwards, backwards),
    ]
