# Generated by Django 5.2.17 on 2026-10-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_registry', '0002_intakepoint_tenant_id_qrcode_tenant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intakepoint',
            name='tenant_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='tenant_id',
            field=models.UUIDField(db_index=True),
        ),
    ]
