# Generated by Django 5.2.17 on 2026-10-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_registry', '0004_enable_row_level_security'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='verification_status',
            field=models.CharField(default='pending', max_length=16),
        ),
    ]
