# Generated by Django 5.2.17 on 2026-10-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_registry', '0005_alter_patient_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
