# Generated by Django 5.2.17 on 2026-10-09 01:58

import uuid
from django.db import migrations, models

from common import rls

#: Table this migration creates. RLS is attached here rather than in 0004
#: because 0004 is already applied; a table created after it with no policy
#: would be a cross-tenant hole in production — the non-owner application
#: role has no BYPASSRLS, so the policy is the only thing standing between
#: tenants. Same pattern as identity_tenancy 0007.
TABLES = ("registry.sequence",)


def _is_postgres(schema_editor) -> bool:
    # Django has no feature flag for row level security, so the backend is
    # checked directly. The fast test suite runs on in-memory SQLite, which
    # has no RLS and no ALTER TABLE ... ENABLE syntax; without this guard the
    # test database cannot even be created.
    return schema_editor.connection.vendor == "postgresql"


def forwards(apps, schema_editor):
    if not _is_postgres(schema_editor):
        return
    schema_editor.execute(rls.enable(TABLES, schema_editor.connection.ops.quote_name))


def backwards(apps, schema_editor):
    if not _is_postgres(schema_editor):
        return
    # Drops the policy but leaves RLS enabled, so the table ends up in
    # PostgreSQL's default-deny state rather than briefly wide open, and the
    # reverse of the whole migration then drops the table.
    schema_editor.execute(rls.disable(TABLES, schema_editor.connection.ops.quote_name))


class Migration(migrations.Migration):

    dependencies = [
        ('patient_registry', '0006_patient_verified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('kind', models.CharField(default='uhid', max_length=16)),
                ('period', models.CharField(max_length=16)),
                ('next_value', models.BigIntegerField(default=1)),
            ],
            options={
                'db_table': 'registry.sequence',
                'unique_together': {('tenant_id', 'kind', 'period')},
            },
        ),
        # RunPython, not RunSQL: Django 5.2's RunSQL accepts SQL strings only,
        # and the quoting here has to come from the live connection — same
        # rationale as the 0004 RLS migrations.
        migrations.RunPython(forwards, backwards),
    ]
