# Generated by Django 5.2.17 on 2026-10-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_registry', '0007_patientsequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='intake_channel',
            field=models.CharField(blank=True, choices=[('counter', 'Counter'), ('abha_qr', 'ABHA QR (Scan and Share)'), ('appointment', 'Appointment')], default='', max_length=16),
        ),
    ]
