# Generated by Django 5.2.17 on 2026-10-09 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity_tenancy', '0009_configrevision_and_bed_active'),
        ('patient_registry', '0010_patient_field_encryption'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_codes', to='identity_tenancy.department'),
        ),
    ]
