# Generated by Django 5.2.17 on 2026-10-01 17:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField(null=True)),
                ('action', models.CharField(max_length=16)),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.CharField(max_length=64)),
                ('reason', models.TextField(null=True)),
                ('source_ip', models.GenericIPAddressField(null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('hash_chain', models.CharField(default='', max_length=128)),
            ],
            options={
                'db_table': 'audit.event',
                'indexes': [models.Index(fields=['tenant_id', 'entity_type', 'entity_id'], name='audit.event_tenant__6a2208_idx'), models.Index(fields=['tenant_id', 'occurred_at'], name='audit.event_tenant__380d1c_idx')],
            },
        ),
    ]
