# Generated by Django 5.2.17 on 2026-10-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_enable_row_level_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='source',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
