# Generated by Django 5.2.17 on 2026-10-01 17:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CAPA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('source_type', models.CharField(max_length=32)),
                ('source_ref', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=400)),
                ('severity', models.CharField(max_length=16)),
                ('owner', models.UUIDField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(default='raised', max_length=32)),
                ('rca_method', models.CharField(max_length=32, null=True)),
                ('root_causes', models.JSONField(null=True)),
                ('corrective_actions', models.JSONField(null=True)),
                ('preventive_actions', models.JSONField(null=True)),
                ('effectiveness_indicator_id', models.UUIDField(null=True)),
                ('effectiveness_check_date', models.DateField(null=True)),
                ('closed_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'quality.capa',
            },
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'quality.framework',
            },
        ),
        migrations.CreateModel(
            name='QualityFact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('source_module', models.CharField(max_length=64)),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'quality.fact',
            },
        ),
        migrations.CreateModel(
            name='FrameworkEdition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edition', models.CharField(max_length=64)),
                ('effective_from', models.DateField()),
                ('status', models.CharField(default='current', max_length=16)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='quality_os.framework')),
            ],
            options={
                'db_table': 'quality.framework_edition',
            },
        ),
        migrations.CreateModel(
            name='IndicatorSourceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=200)),
                ('document_version', models.CharField(max_length=64)),
                ('source_uri', models.URLField(null=True)),
                ('content_hash', models.CharField(max_length=128)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('licensing_status', models.CharField(default='pending', max_length=32)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_documents', to='quality_os.framework')),
            ],
            options={
                'db_table': 'quality.source_document',
            },
        ),
        migrations.CreateModel(
            name='IndicatorDef',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_code', models.CharField(max_length=64, null=True)),
                ('source_sno', models.IntegerField(null=True)),
                ('source_locator', models.CharField(max_length=128, null=True)),
                ('standard_ref', models.CharField(max_length=64, null=True)),
                ('scope_type', models.CharField(max_length=32)),
                ('scope_code', models.CharField(max_length=64, null=True)),
                ('name', models.CharField(max_length=200)),
                ('dimension', models.CharField(max_length=64, null=True)),
                ('unit', models.CharField(max_length=32)),
                ('direction', models.CharField(max_length=16, null=True)),
                ('periodicity', models.CharField(max_length=32)),
                ('definition', models.TextField()),
                ('numerator_spec', models.JSONField(null=True)),
                ('denominator_spec', models.JSONField(null=True)),
                ('formula_operator', models.CharField(max_length=64, null=True)),
                ('calculation_mode', models.CharField(default='auto', max_length=32)),
                ('sampling_required', models.BooleanField(default=False)),
                ('sampling_method', models.CharField(max_length=128, null=True)),
                ('sample_size_spec', models.JSONField(null=True)),
                ('reporting_lag_days', models.IntegerField(null=True)),
                ('source_of_data', models.CharField(max_length=200, null=True)),
                ('system_capture_guide', models.TextField(null=True)),
                ('applicability', models.JSONField(null=True)),
                ('definition_version', models.IntegerField(default=1)),
                ('status', models.CharField(default='active', max_length=16)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='quality_os.frameworkedition')),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='quality_os.indicatorsourcedocument')),
            ],
            options={
                'db_table': 'quality.indicator_def',
            },
        ),
        migrations.CreateModel(
            name='IndicatorValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('facility_id', models.UUIDField(db_index=True)),
                ('department_id', models.UUIDField(db_index=True, null=True)),
                ('definition_version', models.IntegerField()),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('numerator', models.FloatField(null=True)),
                ('denominator', models.FloatField(null=True)),
                ('value', models.FloatField(null=True)),
                ('status', models.CharField(default='draft', max_length=16)),
                ('computed_at', models.DateTimeField(null=True)),
                ('data_quality_flags', models.JSONField(default=list)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='quality_os.indicatordef')),
            ],
            options={
                'db_table': 'quality.indicator_value',
                'indexes': [models.Index(fields=['tenant_id', 'indicator_id', 'period_start'], name='quality.ind_tenant__04128c_idx')],
            },
        ),
    ]
