# Generated by Django 5.2.17 on 2026-10-01 17:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OPDEncounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('department_id', models.UUIDField(db_index=True)),
                ('visit_type', models.CharField(max_length=16)),
                ('referral_in_source', models.CharField(max_length=128, null=True)),
                ('referral_out', models.BooleanField(default=False)),
                ('registration_time', models.DateTimeField()),
                ('consultation_start', models.DateTimeField(null=True)),
                ('consultation_end', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'opd.encounter',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('department_id', models.UUIDField(db_index=True)),
                ('series', models.CharField(max_length=32)),
                ('number', models.IntegerField()),
                ('priority', models.IntegerField(default=0)),
                ('status', models.CharField(default='waiting', max_length=16)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(null=True)),
                ('done_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'opd.token',
                'indexes': [models.Index(fields=['tenant_id', 'department_id', 'status'], name='opd.token_tenant__928bba_idx')],
            },
        ),
    ]
