# Generated by Django 5.2.17 on 2026-10-09 01:58

import uuid
from django.db import migrations, models

from common import rls

#: Table this migration creates. RLS is attached here rather than in 0004
#: because 0004 is already applied; a table created after it with no policy
#: would be a cross-tenant hole in production — the non-owner application
#: role has no BYPASSRLS, so the policy is the only thing standing between
#: tenants. Same pattern as identity_tenancy 0007.
TABLES = ("opd.token_series",)


def _is_postgres(schema_editor) -> bool:
    # Django has no feature flag for row level security, so the backend is
    # checked directly. The fast test suite runs on in-memory SQLite, which
    # has no RLS and no ALTER TABLE ... ENABLE syntax; without this guard the
    # test database cannot even be created.
    return schema_editor.connection.vendor == "postgresql"


def forwards(apps, schema_editor):
    if not _is_postgres(schema_editor):
        return
    schema_editor.execute(rls.enable(TABLES, schema_editor.connection.ops.quote_name))


def backwards(apps, schema_editor):
    if not _is_postgres(schema_editor):
        return
    # Drops the policy but leaves RLS enabled, so the table ends up in
    # PostgreSQL's default-deny state rather than briefly wide open, and the
    # reverse of the whole migration then drops the table.
    schema_editor.execute(rls.disable(TABLES, schema_editor.connection.ops.quote_name))


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0004_enable_row_level_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('facility_id', models.UUIDField(db_index=True)),
                ('department_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('prefix', models.CharField(default='GEN', max_length=16)),
                ('next_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'opd.token_series',
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'facility_id', 'department_id'), name='opd_token_series_tenant_facility_department_uniq', nulls_distinct=False)],
            },
        ),
        # RunPython, not RunSQL: Django 5.2's RunSQL accepts SQL strings only,
        # and the quoting here has to come from the live connection — same
        # rationale as the 0004 RLS migrations.
        migrations.RunPython(forwards, backwards),
    ]
