# Generated by Django 5.2.17 on 2026-10-01 17:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('doc_type', models.CharField(max_length=64)),
                ('content', models.JSONField()),
                ('version', models.IntegerField(default=1)),
                ('amended_from', models.UUIDField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField()),
            ],
            options={
                'db_table': 'emr.document',
            },
        ),
        migrations.CreateModel(
            name='ProblemList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('onset_date', models.DateField(null=True)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'emr.problem',
            },
        ),
        migrations.CreateModel(
            name='SafetyEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(max_length=64)),
                ('severity', models.CharField(max_length=16)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'emr.safety_event',
            },
        ),
    ]
