# Generated by Django 5.2.17, then extended with the tenant_id backfill.
#
# Expand phase of the tenancy fix. tenant_id is added nullable here and backfilled
# from the owning parent row; migration 0003 tightens it to NOT NULL. The split is
# deliberate: PostgreSQL cannot add a NOT NULL column to a populated table, and a
# default would be a guess at which tenant owns each row - the cross-tenant
# leakage the architecture doc section 7 names as the top risk.
from django.db import migrations, models

from common.tenant_migration import assert_no_orphans, backfill_tenant_id


def forwards(apps, schema_editor):
    # emr.problem derives its tenant from registry.patient.patient_id.
    backfill_tenant_id(
        target_table='emr.problem',
        parent_table='registry.patient',
        parent_column='patient_id',
    )
    assert_no_orphans(target_table='emr.problem')


def backwards(apps, schema_editor):
    # Reversing only drops the column; the rows themselves are untouched.
    pass



class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0001_initial'),
        ('patient_registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemlist',
            name='tenant_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='problemlist',
            index=models.Index(fields=['tenant_id', 'patient_id', 'resolved'], name='emr.problem_tenant__3c4ace_idx'),
        ),
        migrations.RunPython(forwards, backwards),
    ]
