# Generated by Django 5.2.17 on 2026-10-01 17:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=64)),
                ('abdm_hip_id', models.CharField(blank=True, max_length=64, null=True)),
                ('abdm_facility_id', models.CharField(blank=True, max_length=64, null=True)),
                ('hfr_id', models.CharField(blank=True, max_length=64, null=True)),
                ('abdm_registration_status', models.CharField(default='pending', max_length=32)),
                ('address', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'identity.facility',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('tier', models.CharField(default='standard', max_length=32)),
                ('accreditation_profile', models.JSONField(default=list)),
                ('db_mode', models.CharField(default='shared', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'identity.tenant',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('opd_enabled', models.BooleanField(default=False)),
                ('ipd_enabled', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='identity_tenancy.facility')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='identity_tenancy.tenant')),
            ],
            options={
                'db_table': 'identity.department',
            },
        ),
        migrations.CreateModel(
            name='ServiceUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('type_tag', models.CharField(max_length=64)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_units', to='identity_tenancy.facility')),
            ],
            options={
                'db_table': 'identity.service_unit',
            },
        ),
        migrations.CreateModel(
            name='StaffPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=120)),
                ('specialty', models.CharField(blank=True, max_length=120, null=True)),
                ('sanctioned', models.IntegerField(default=0)),
                ('in_position', models.IntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_positions', to='identity_tenancy.department')),
            ],
            options={
                'db_table': 'identity.staff_position',
            },
        ),
        migrations.AddField(
            model_name='facility',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='identity_tenancy.tenant'),
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('type_tag', models.CharField(max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='identity_tenancy.department')),
            ],
            options={
                'db_table': 'identity.ward',
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bed_number', models.CharField(max_length=32)),
                ('functional', models.BooleanField(default=True)),
                ('occupied', models.BooleanField(default=False)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='identity_tenancy.ward')),
            ],
            options={
                'db_table': 'identity.bed',
            },
        ),
    ]
