# Generated by Django 5.2.17, then extended with the tenant_id backfill.
#
# Expand phase of the tenancy fix. tenant_id is added nullable here and backfilled
# from the owning parent row; migration 0003 tightens it to NOT NULL. The split is
# deliberate: PostgreSQL cannot add a NOT NULL column to a populated table, and a
# default would be a guess at which tenant owns each row - the cross-tenant
# leakage the architecture doc section 7 names as the top risk.
from django.db import migrations, models

from common.tenant_migration import assert_no_orphans, backfill_tenant_id


def forwards(apps, schema_editor):
    # identity.ward derives its tenant from identity.department.department_id.
    backfill_tenant_id(
        target_table='identity.ward',
        parent_table='identity.department',
        parent_column='department_id',
    )
    # identity.bed derives its tenant from identity.ward.ward_id.
    backfill_tenant_id(
        target_table='identity.bed',
        parent_table='identity.ward',
        parent_column='ward_id',
    )
    # identity.service_unit derives its tenant from identity.facility.facility_id.
    backfill_tenant_id(
        target_table='identity.service_unit',
        parent_table='identity.facility',
        parent_column='facility_id',
    )
    # identity.staff_position derives its tenant from identity.department.department_id.
    backfill_tenant_id(
        target_table='identity.staff_position',
        parent_table='identity.department',
        parent_column='department_id',
    )
    assert_no_orphans(target_table='identity.ward')
    assert_no_orphans(target_table='identity.bed')
    assert_no_orphans(target_table='identity.service_unit')
    assert_no_orphans(target_table='identity.staff_position')


def backwards(apps, schema_editor):
    # Reversing only drops the column; the rows themselves are untouched.
    pass



class Migration(migrations.Migration):

    dependencies = [
        ('identity_tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='tenant_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceunit',
            name='tenant_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='staffposition',
            name='tenant_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='tenant_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['tenant_id', 'ward', 'functional'], name='identity.be_tenant__f146e1_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceunit',
            index=models.Index(fields=['tenant_id', 'facility', 'type_tag'], name='identity.se_tenant__f549be_idx'),
        ),
        migrations.AddIndex(
            model_name='staffposition',
            index=models.Index(fields=['tenant_id', 'department', 'designation'], name='identity.st_tenant__5626e9_idx'),
        ),
        migrations.AddIndex(
            model_name='ward',
            index=models.Index(fields=['tenant_id', 'department', 'active'], name='identity.wa_tenant__566f10_idx'),
        ),
        migrations.RunPython(forwards, backwards),
    ]
