# Generated by Django 5.2.17 on 2026-10-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity_tenancy', '0002_bed_tenant_id_serviceunit_tenant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='tenant_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='serviceunit',
            name='tenant_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='staffposition',
            name='tenant_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='ward',
            name='tenant_id',
            field=models.UUIDField(db_index=True),
        ),
    ]
