# Generated by Django 5.2.17 on 2026-10-08 14:08

import uuid
from django.db import migrations, models

from common import rls

#: The table this migration creates. RLS is attached here rather than in
#: 0004/0006 because those migrations are already applied; a table created
#: after them with no policy would be a cross-tenant hole in production —
#: the non-owner application role has no BYPASSRLS, so the policy is the
#: only thing standing between tenants (plan Global Constraints; "every new
#: table after 0004 needs its own policy DDL").
TABLES = ("identity.setup_progress",)


def _is_postgres(schema_editor) -> bool:
    # Django has no feature flag for row level security, so the backend is
    # checked directly. The fast test suite runs on in-memory SQLite, which
    # has no RLS and no ALTER TABLE ... ENABLE syntax; without this guard the
    # test database cannot even be created. SQLite also has no equivalent, so
    # tenant isolation there is enforced by TenantScopedQuerysetMixin alone —
    # which is why the isolation gate in tests/integration/test_rls_isolation.py
    # requires a real PostgreSQL.
    return schema_editor.connection.vendor == "postgresql"


def forwards(apps, schema_editor):
    if not _is_postgres(schema_editor):
        return
    schema_editor.execute(rls.enable(TABLES, schema_editor.connection.ops.quote_name))


def backwards(apps, schema_editor):
    if not _is_postgres(schema_editor):
        return
    # Drops the policy but leaves RLS enabled, so the table ends up in
    # PostgreSQL's default-deny state rather than briefly wide open, and the
    # reverse of the whole migration then drops the table.
    schema_editor.execute(rls.disable(TABLES, schema_editor.connection.ops.quote_name))


class Migration(migrations.Migration):

    dependencies = [
        ('identity_tenancy', '0006_enable_rls_identity_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('step_key', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('complete', 'Complete')], default='pending', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'identity.setup_progress',
                'indexes': [models.Index(fields=['tenant_id', 'step_key'], name='identity.se_tenant__796157_idx')],
                'unique_together': {('tenant_id', 'step_key')},
            },
        ),
        # RunPython, not RunSQL: Django 5.2's RunSQL accepts SQL strings only,
        # and the quoting here has to come from the live connection — same
        # rationale as the 0004/0006 RLS migrations.
        migrations.RunPython(forwards, backwards),
    ]
