# Generated by Django 5.2.17 on 2026-10-08 14:51

import uuid
from django.db import migrations, models

from common import rls

#: The tables this migration creates. RLS is attached here rather than in
#: 0004/0006 because those migrations are already applied; a table created
#: after them with no policy would be a cross-tenant hole in production —
#: the non-owner application role has no BYPASSRLS, so the policy is the
#: only thing standing between tenants (plan Global Constraints; "every new
#: table after 0004 needs its own policy DDL"). The same structure as
#: 0007_setupprogress, whose RunPython this mirrors.
TABLES = ("identity.reference_data", "identity.baseline_input")


def _is_postgres(schema_editor) -> bool:
    # Django has no feature flag for row level security, so the backend is
    # checked directly. The fast test suite runs on in-memory SQLite, which
    # has no RLS and no ALTER TABLE ... ENABLE syntax; without this guard the
    # test database cannot even be created. SQLite also has no equivalent, so
    # tenant isolation there is enforced by TenantScopedQuerysetMixin alone —
    # which is why the isolation gate in tests/integration/test_rls_isolation.py
    # requires a real PostgreSQL.
    return schema_editor.connection.vendor == "postgresql"


def forwards(apps, schema_editor):
    if not _is_postgres(schema_editor):
        return
    schema_editor.execute(rls.enable(TABLES, schema_editor.connection.ops.quote_name))


def backwards(apps, schema_editor):
    if not _is_postgres(schema_editor):
        return
    # Drops the policy but leaves RLS enabled, so each table ends up in
    # PostgreSQL's default-deny state rather than briefly wide open, and the
    # reverse of the whole migration then drops the tables.
    schema_editor.execute(rls.disable(TABLES, schema_editor.connection.ops.quote_name))


class Migration(migrations.Migration):

    dependencies = [
        ('identity_tenancy', '0007_setupprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaselineInput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('indicator_source_code', models.CharField(max_length=64)),
                ('period', models.CharField(max_length=16)),
                ('value', models.FloatField()),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('imported', 'Imported')], default='manual', max_length=16)),
            ],
            options={
                'db_table': 'identity.baseline_input',
                'indexes': [models.Index(fields=['tenant_id', 'indicator_source_code', 'period'], name='identity.ba_tenant__02e3d6_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReferenceData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('kind', models.CharField(choices=[('catchment_population', 'Catchment population'), ('ambulance', 'Ambulance'), ('essential_commodity', 'Essential commodity')], max_length=32)),
                ('key', models.CharField(max_length=128)),
                ('value', models.JSONField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'identity.reference_data',
                'indexes': [models.Index(fields=['tenant_id', 'kind', 'key'], name='identity.re_tenant__165ac0_idx')],
                'unique_together': {('tenant_id', 'kind', 'key')},
            },
        ),
        # RunPython, not RunSQL: Django 5.2's RunSQL accepts SQL strings only,
        # and the quoting here has to come from the live connection — same
        # rationale as the 0004/0006/0007 RLS migrations.
        migrations.RunPython(forwards, backwards),
    ]
