# Generated by Django 5.2.17 on 2026-10-08 16:13

import uuid
from django.db import migrations, models

from common import rls

#: The table this migration creates. RLS is attached here rather than in
#: 0004/0006 because those migrations are already applied; a table created
#: after them with no policy would be a cross-tenant hole in production —
#: the non-owner application role has no BYPASSRLS, so the policy is the
#: only thing standing between tenants. The same structure as
#: 0007_setupprogress and 0008_baselineinput_referencedata, whose RunPython
#: this mirrors.
TABLES = ("identity.config_revision",)


def _is_postgres(schema_editor) -> bool:
    # Django has no feature flag for row level security, so the backend is
    # checked directly. The fast test suite runs on in-memory SQLite, which
    # has no RLS and no ALTER TABLE ... ENABLE syntax; without this guard the
    # test database cannot even be created. SQLite also has no equivalent, so
    # tenant isolation there is enforced by TenantScopedQuerysetMixin alone —
    # which is why the isolation gate in tests/integration/test_rls_isolation.py
    # requires a real PostgreSQL.
    return schema_editor.connection.vendor == "postgresql"


def forwards(apps, schema_editor):
    if not _is_postgres(schema_editor):
        return
    schema_editor.execute(rls.enable(TABLES, schema_editor.connection.ops.quote_name))


def backwards(apps, schema_editor):
    if not _is_postgres(schema_editor):
        return
    # Drops the policy but leaves RLS enabled, so the table ends up in
    # PostgreSQL's default-deny state rather than briefly wide open, and the
    # reverse of the whole migration then drops the table.
    schema_editor.execute(rls.disable(TABLES, schema_editor.connection.ops.quote_name))


class Migration(migrations.Migration):

    dependencies = [
        ('identity_tenancy', '0008_baselineinput_referencedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ConfigRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('entity', models.CharField(max_length=32)),
                ('entity_id', models.UUIDField()),
                ('snapshot', models.JSONField()),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_by', models.UUIDField(null=True)),
            ],
            options={
                'db_table': 'identity.config_revision',
                'indexes': [models.Index(fields=['tenant_id', 'entity', 'entity_id'], name='identity.co_tenant__674bd1_idx')],
            },
        ),
        # RunPython, not RunSQL: Django 5.2's RunSQL accepts SQL strings only,
        # and the quoting here has to come from the live connection — same
        # rationale as the 0004/0006/0007/0008 RLS migrations.
        migrations.RunPython(forwards, backwards),
    ]
