# Generated by Django 5.2.17 on 2026-10-01 17:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admission_id', models.UUIDField(db_index=True)),
                ('device_type', models.CharField(max_length=64)),
                ('inserted_at', models.DateTimeField()),
                ('removed_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'icu.device',
            },
        ),
        migrations.CreateModel(
            name='VitalsFlowsheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('type', models.CharField(max_length=32)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=16)),
                ('source', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'icu.vitals',
                'indexes': [models.Index(fields=['tenant_id', 'patient_id', 'recorded_at'], name='icu.vitals_tenant__237309_idx')],
            },
        ),
    ]
