# Generated by Django 5.2.17, then extended with the tenant_id backfill.
#
# Expand phase of the tenancy fix. tenant_id is added nullable here and backfilled
# from the owning parent row; migration 0003 tightens it to NOT NULL. The split is
# deliberate: PostgreSQL cannot add a NOT NULL column to a populated table, and a
# default would be a guess at which tenant owns each row - the cross-tenant
# leakage the architecture doc section 7 names as the top risk.
from django.db import migrations, models

from common.tenant_migration import require_empty


def forwards(apps, schema_editor):
    require_empty(target_table="integration.adapter")


def backwards(apps, schema_editor):
    # Reversing only drops the column; the rows themselves are untouched.
    pass



class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationadapter',
            name='tenant_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='integrationadapter',
            unique_together={('tenant_id', 'name')},
        ),
        migrations.AddIndex(
            model_name='integrationadapter',
            index=models.Index(fields=['tenant_id', 'name', 'active'], name='integration_tenant__7baa7a_idx'),
        ),
        migrations.RunPython(forwards, backwards),
    ]
