# Generated by Django 5.2.17 on 2026-10-02 06:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0004_enable_row_level_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('url', models.URLField()),
                ('events', models.JSONField(default=list)),
                ('secret', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'integration.webhook',
                'indexes': [models.Index(fields=['tenant_id', 'active'], name='integration_tenant__a6d669_idx')],
            },
        ),
    ]
