# Generated by Django 5.2.17 on 2026-10-01 17:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('category', models.CharField(max_length=16)),
                ('arrival_time', models.DateTimeField(auto_now_add=True)),
                ('first_assessment_time', models.DateTimeField(null=True)),
                ('mlc_flag', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'emergency.triage',
            },
        ),
    ]
