# Generated by Django 5.2.17 on 2026-10-01 17:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('formulary_id', models.UUIDField(db_index=True)),
                ('substituted', models.BooleanField(default=False)),
                ('dispensed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pharmacy.dispense',
            },
        ),
        migrations.CreateModel(
            name='Formulary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('generic', models.BooleanField(default=False)),
                ('high_alert', models.BooleanField(default=False)),
                ('lasa', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'pharmacy.formulary',
            },
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('formulary_id', models.UUIDField(db_index=True)),
                ('batch_no', models.CharField(max_length=64)),
                ('expiry', models.DateField()),
                ('quantity', models.IntegerField()),
                ('stock_out_day', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'pharmacy.stock_batch',
            },
        ),
    ]
