# Generated by Django 5.2.17, then extended with the tenant_id backfill.
#
# Expand phase of the tenancy fix. tenant_id is added nullable here and backfilled
# from the owning parent row; migration 0003 tightens it to NOT NULL. The split is
# deliberate: PostgreSQL cannot add a NOT NULL column to a populated table, and a
# default would be a guess at which tenant owns each row - the cross-tenant
# leakage the architecture doc section 7 names as the top risk.
from django.db import migrations, models

from common.tenant_migration import assert_no_orphans, backfill_tenant_id


def forwards(apps, schema_editor):
    # pharmacy.stock_batch derives its tenant from pharmacy.formulary.formulary_id.
    backfill_tenant_id(
        target_table='pharmacy.stock_batch',
        parent_table='pharmacy.formulary',
        parent_column='formulary_id',
    )
    # pharmacy.dispense derives its tenant from registry.patient.patient_id.
    backfill_tenant_id(
        target_table='pharmacy.dispense',
        parent_table='registry.patient',
        parent_column='patient_id',
    )
    assert_no_orphans(target_table='pharmacy.stock_batch')
    assert_no_orphans(target_table='pharmacy.dispense')


def backwards(apps, schema_editor):
    # Reversing only drops the column; the rows themselves are untouched.
    pass



class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
        ('patient_registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispense',
            name='tenant_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='tenant_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='dispense',
            index=models.Index(fields=['tenant_id', 'patient_id', 'dispensed_at'], name='pharmacy.di_tenant__a7f4d3_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['tenant_id', 'formulary_id', 'stock_out_day'], name='pharmacy.st_tenant__1c4e8d_idx'),
        ),
        migrations.RunPython(forwards, backwards),
    ]
