# Generated by Django 5.2.17 on 2026-10-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_dispense_tenant_id_stockbatch_tenant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispense',
            name='tenant_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='tenant_id',
            field=models.UUIDField(db_index=True),
        ),
    ]
