# Generated by Django 5.2.17 on 2026-10-01 17:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('donation_id', models.UUIDField(db_index=True)),
                ('component_type', models.CharField(max_length=32)),
                ('blood_group', models.CharField(max_length=8)),
                ('status', models.CharField(default='available', max_length=32)),
                ('collection_date', models.DateField()),
                ('expiry_date', models.DateField()),
            ],
            options={
                'db_table': 'bbk.component',
            },
        ),
        migrations.CreateModel(
            name='CrossMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requisition_id', models.UUIDField(db_index=True)),
                ('result', models.CharField(max_length=32)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bbk.crossmatch',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('donor_id', models.UUIDField(db_index=True)),
                ('collection_time', models.DateTimeField(auto_now_add=True)),
                ('testing_status', models.CharField(default='pending', max_length=32)),
                ('mandatory_tests', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'bbk.donation',
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('blood_group', models.CharField(max_length=8)),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bbk.donor',
            },
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('patient_id', models.UUIDField(db_index=True, null=True)),
                ('component_id', models.UUIDField(db_index=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('issued_at', models.DateTimeField(null=True)),
                ('source', models.CharField(max_length=32, null=True)),
            ],
            options={
                'db_table': 'bbk.requisition',
            },
        ),
        migrations.CreateModel(
            name='TransfusionReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requisition_id', models.UUIDField(db_index=True)),
                ('component_id', models.UUIDField(db_index=True)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('reaction_type', models.CharField(max_length=64)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bbk.reaction',
            },
        ),
    ]
