# Generated by Django 5.2.17, then extended with the tenant_id backfill.
#
# Expand phase of the tenancy fix. tenant_id is added nullable here and backfilled
# from the owning parent row; migration 0003 tightens it to NOT NULL. The split is
# deliberate: PostgreSQL cannot add a NOT NULL column to a populated table, and a
# default would be a guess at which tenant owns each row - the cross-tenant
# leakage the architecture doc section 7 names as the top risk.
from django.db import migrations, models

from common.tenant_migration import assert_no_orphans, backfill_tenant_id


def forwards(apps, schema_editor):
    # bbk.donation derives its tenant from bbk.donor.donor_id.
    backfill_tenant_id(
        target_table='bbk.donation',
        parent_table='bbk.donor',
        parent_column='donor_id',
    )
    # bbk.crossmatch derives its tenant from bbk.requisition.requisition_id.
    backfill_tenant_id(
        target_table='bbk.crossmatch',
        parent_table='bbk.requisition',
        parent_column='requisition_id',
    )
    # bbk.reaction derives its tenant from bbk.requisition.requisition_id.
    backfill_tenant_id(
        target_table='bbk.reaction',
        parent_table='bbk.requisition',
        parent_column='requisition_id',
    )
    assert_no_orphans(target_table='bbk.donation')
    assert_no_orphans(target_table='bbk.crossmatch')
    assert_no_orphans(target_table='bbk.reaction')


def backwards(apps, schema_editor):
    # Reversing only drops the column; the rows themselves are untouched.
    pass



class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossmatch',
            name='tenant_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='tenant_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='transfusionreaction',
            name='tenant_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='crossmatch',
            index=models.Index(fields=['tenant_id', 'requisition_id', 'result'], name='bbk.crossma_tenant__93426e_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['tenant_id', 'donor_id', 'testing_status'], name='bbk.donatio_tenant__92178b_idx'),
        ),
        migrations.AddIndex(
            model_name='transfusionreaction',
            index=models.Index(fields=['tenant_id', 'patient_id', 'recorded_at'], name='bbk.reactio_tenant__552712_idx'),
        ),
        migrations.RunPython(forwards, backwards),
    ]
