# Generated by Django 5.2.17 on 2026-10-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0002_crossmatch_tenant_id_donation_tenant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crossmatch',
            name='tenant_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='tenant_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='transfusionreaction',
            name='tenant_id',
            field=models.UUIDField(db_index=True),
        ),
    ]
