# Generated by Django 5.2.17 on 2026-10-01 17:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BedStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bed_id', models.UUIDField(db_index=True)),
                ('ward_id', models.UUIDField(db_index=True)),
                ('occupied', models.BooleanField(default=False)),
                ('patient_id', models.UUIDField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ipd.bed_status',
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('department_id', models.UUIDField(db_index=True)),
                ('ward_id', models.UUIDField(db_index=True)),
                ('bed_id', models.UUIDField(db_index=True)),
                ('admission_time', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=64)),
                ('diagnosis', models.TextField(null=True)),
                ('responsible_clinician_id', models.UUIDField(null=True)),
                ('discharged_at', models.DateTimeField(null=True)),
                ('disposition', models.CharField(choices=[('routine', 'Routine'), ('lama', 'LAMA'), ('absconded', 'Absconded'), ('referred', 'Referred'), ('death', 'Death'), ('other', 'Other')], max_length=32, null=True)),
                ('discharge_summary', models.TextField(null=True)),
                ('transfer_from', models.UUIDField(null=True)),
                ('transfer_to', models.UUIDField(null=True)),
                ('transfer_reason', models.TextField(null=True)),
            ],
            options={
                'db_table': 'ipd.admission',
                'indexes': [models.Index(fields=['tenant_id', 'patient_id'], name='ipd.admissi_tenant__85c358_idx'), models.Index(fields=['tenant_id', 'bed_id'], name='ipd.admissi_tenant__8c532f_idx')],
            },
        ),
        migrations.CreateModel(
            name='CensusSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('facility_id', models.UUIDField(db_index=True)),
                ('ward_id', models.UUIDField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'ipd.census_snapshot',
                'unique_together': {('tenant_id', 'ward_id', 'date')},
            },
        ),
    ]
