# Generated by Django 5.2.17 on 2026-10-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0002_bedstatus_tenant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedstatus',
            name='tenant_id',
            field=models.UUIDField(db_index=True),
        ),
    ]
